### ISSUE TITLE
Recipe should set result item gold cost automatically

### ISSUE THREAD

**Issue by Overkane** [Frotty/wurst-item-recipes#5]
For example we have this piece of code:
```
public constant ADEPT_STAFF_RECIPE = new ItemRecipe()
..gold(190)
..setRequiredItems(APPRENTICE_STAFF_ITEM.getNewId(), APPRENTICE_STAFF_ITEM.getNewId())
..setResultItem(ADEPT_STAFF_ITEM)
```
Setting result item should calculate and set gold cost for result item. So in this example ADEPT_STAFF_ITEM cost should be 190 + cost of two APPRENTICE_STAFF_ITEM which can be recipe items by itself and it cost should be also calculated automatically if that's the case.

Otherwise it's quite tedious to set gold cost for every recipe item, since if you adjust gold cost of one basic item, then you have to adjust gold cost for every item in which recipe it was used.

**Comment by Frotty** [comment]
Don't think that will work since recipes are created at runtime, not compiletime.

**Comment by Overkane** [comment]
I mean RecipeItem has goldCost variable which can be set whenever you like, right?

**Comment by Overkane** [comment]
Implemented
